[target]
crate = "actix"
version = "0.10.0"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/address/channel.rs:887:1: 887:43"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/address/channel.rs:888:1: 888:43"