[target]
crate = "arc-string-interner"
version = "0.1.0"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "independently fixed"
location = "src/lib.rs:250:1: 255:2"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "independently fixed"
location = "src/lib.rs:256:1: 261:2"
