[target]
crate = "async_logger"
version = "0.3.1"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/buf.rs:304:1: 304:34"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/buf.rs:303:1: 303:34"
