[target]
crate = "froop"
version = "0.1.1"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/peg.rs:11:1: 11:37"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/peg.rs:12:1: 12:37"
