[target]
crate = "parity-scale-codec"
version = "2.0.0"
indexed_version = "1.3.1"

[[bugs]]
analyzer = "UnsafeDataflow"
bug_class = "InconsistencyAmplification"
reason = "experimetal"
location = "src/codec.rs:578:5: 605:6"
