[target]
crate = "rsdb"
version = "0.12.1"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/thread_cache.rs:20:1: 20:42"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/thread_cache.rs:21:1: 21:42"
