[target]
crate = "secp256k1"
version = "0.17.2"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/lib.rs:540:1: 540:49"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/lib.rs:542:1: 542:49"
