[target]
crate = "shipyard"
version = "0.4.1"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/atomic_refcell.rs:23:1: 23:52"

[[bugs]]
analyzer = "SendSyncVariance"
bug_class = "SendSyncVariance"
reason = "internal"
location = "src/atomic_refcell.rs:25:1: 25:52"
